table d_empresa
	lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000001

	column ticker
		dataType: string
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000002
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column nome
		dataType: string
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000003
		summarizeBy: none
		sourceColumn: nome

		annotation SummarizationSetBy = Automatic

	column setor
		dataType: string
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000004
		summarizeBy: none
		sourceColumn: setor

		annotation SummarizationSetBy = Automatic

	column preco_atual
		dataType: double
		formatString: #,0.00
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000005
		summarizeBy: none
		sourceColumn: preco_atual

		annotation SummarizationSetBy = Automatic

	column pl
		dataType: double
		formatString: #,0.00
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000006
		summarizeBy: none
		sourceColumn: pl

		annotation SummarizationSetBy = Automatic

	column min_52s
		dataType: double
		formatString: #,0.00
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000007
		summarizeBy: none
		sourceColumn: min_52s

		annotation SummarizationSetBy = Automatic

	column max_52s
		dataType: double
		formatString: #,0.00
		lineageTag: b1a7e0c2-8001-4aaa-8bbb-000000000008
		summarizeBy: none
		sourceColumn: max_52s

		annotation SummarizationSetBy = Automatic

	partition d_empresa = m
		mode: import
		source =
				let
				    Tickers = List.Transform(Text.Split(IbovTickers, ","), each Text.Trim(_)),
				    Cotacoes = Table.Combine(List.Transform(Tickers, each fnBrapiQuote(_))),
				    respList = Web.Contents(UrlBaseBrapi, [RelativePath = "api/quote/list", Query = [token = BrapiToken, limit = "1000"]]),
				    jsonList = try Json.Document(respList) otherwise null,
				    stocks = if jsonList = null then {} else try jsonList[stocks] otherwise {},
				    tblList = if List.IsEmpty(stocks) then #table(type table [stock = text, sector = text], {}) else Table.FromRecords(stocks),
				    setores = Table.SelectColumns(tblList, {"stock", "sector"}, MissingField.UseNull),
				    setoresRen = Table.RenameColumns(setores, {{"stock", "ticker"}, {"sector", "setor"}}),
				    juncao = Table.NestedJoin(Cotacoes, {"ticker"}, setoresRen, {"ticker"}, "s", JoinKind.LeftOuter),
				    comSetor = Table.ExpandTableColumn(juncao, "s", {"setor"}, {"setor"}),
				    tipos = Table.TransformColumnTypes(comSetor, {{"ticker", type text}, {"nome", type text}, {"setor", type text}, {"preco_atual", type number}, {"pl", type number}, {"min_52s", type number}, {"max_52s", type number}}),
				    ordem = Table.SelectColumns(tipos, {"ticker", "nome", "setor", "preco_atual", "pl", "min_52s", "max_52s"})
				in
				    ordem

	annotation PBI_ResultType = Table
